import lsst.afw.cameraGeom.cameraConfig
assert type(config)==lsst.afw.cameraGeom.cameraConfig.CameraConfig, 'config is of type %s.%s instead of lsst.afw.cameraGeom.cameraConfig.CameraConfig' % (type(config).__module__, type(config).__name__)
config.plateScale=1.0
config.transformDict.nativeSys='FocalPlane'
config.transformDict.transforms={}
config.transformDict.transforms['Focal_Plane_Pixels']=lsst.afw.geom.transformConfig.TransformConfig()
config.transformDict.transforms['Focal_Plane_Pixels'].transform['multi'].transformDict=None
config.transformDict.transforms['Focal_Plane_Pixels'].transform['affine'].translation=[0.0, 0.0]
config.transformDict.transforms['Focal_Plane_Pixels'].transform['affine'].linear=[1.0, 0.0, 0.0, 1.0]
config.transformDict.transforms['Focal_Plane_Pixels'].transform['radial'].coeffs=None
config.transformDict.transforms['Focal_Plane_Pixels'].transform.name='affine'
config.transformDict.transforms['Pupil']=lsst.afw.geom.transformConfig.TransformConfig()
config.transformDict.transforms['Pupil'].transform['multi'].transformDict=None
config.transformDict.transforms['Pupil'].transform['affine'].translation=[0.0, 0.0]
config.transformDict.transforms['Pupil'].transform['affine'].linear=[1.0, 0.0, 0.0, 1.0]
config.transformDict.transforms['Pupil'].transform['radial'].coeffs=None
config.transformDict.transforms['Pupil'].transform.name='affine'
config.detectorList={}
config.detectorList[0]=lsst.afw.cameraGeom.cameraConfig.DetectorConfig()
config.detectorList[0].bbox_y0=0
config.detectorList[0].bbox_y1=4299
config.detectorList[0].bbox_x1=4415
config.detectorList[0].bbox_x0=0
config.detectorList[0].name='0_00'
config.detectorList[0].pixelSize_x=1.0
config.detectorList[0].transformDict.nativeSys=None
config.detectorList[0].transformDict.transforms=None
config.detectorList[0].refpos_x=1023.5
config.detectorList[0].refpos_y=2087.5
config.detectorList[0].pixelSize_y=1.0
config.detectorList[0].detectorType=0
config.detectorList[0].offset_x=14861.08
config.detectorList[0].offset_y=-6629.29
config.detectorList[0].transposeDetector=None
config.detectorList[0].yawDeg=180.0000000
config.detectorList[0].rollDeg=0.0
config.detectorList[0].serial='0'
config.detectorList[0].pitchDeg=0.0
config.detectorList[0].id=0
config.radialCoeffs=None
config.name='PFS'
